### ISSUE TITLE
Brave browser issue

### ISSUE THREAD

**Issue by lichtner** [jacob-ebey/remix-shadcn#8]
After any changes in `_index.html ` and hot reload in brave browser page stay without any styles. and in console are 12 issues:

    Warning: Expected server HTML to contain a matching <head> in <html>.
    at head
    at html
    at ThemeSwitcherSafeHTML (http://localhost:3000/app/components/theme-switcher.tsx:3:3)
    at App (http://localhost:3000/app/root.tsx:9:3)
    at Root
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:404:5)
    at RenderErrorBoundary (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:364:5)
    at DataRoutes (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:1393:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:745:15)
    at RouterProvider (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:1210:5)
    at RemixErrorBoundary (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:3455:5)
    at RemixBrowser (http://localhost:3000/node_modules/.vite/deps/@remix-run_react.js?v=182ba9fc:4112:46)
    
    Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (chunk-2CHT42SU.js?v=182ba9fc:9491:17)
    at tryToClaimNextHydratableInstance (chunk-2CHT42SU.js?v=182ba9fc:9512:15)
    at updateHostComponent (chunk-2CHT42SU.js?v=182ba9fc:14789:13)
    at beginWork (chunk-2CHT42SU.js?v=182ba9fc:15923:22)
    at HTMLUnknownElement.callCallback2 (chunk-2CHT42SU.js?v=182ba9fc:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-2CHT42SU.js?v=182ba9fc:3699:24)
    at invokeGuardedCallback (chunk-2CHT42SU.js?v=182ba9fc:3733:39)
    at beginWork$1 (chunk-2CHT42SU.js?v=182ba9fc:19761:15)
    at performUnitOfWork (chunk-2CHT42SU.js?v=182ba9fc:19194:20)
    at workLoopConcurrent (chunk-2CHT42SU.js?v=182ba9fc:19185:13)

    Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (chunk-2CHT42SU.js?v=182ba9fc:9491:17)
    at tryToClaimNextHydratableInstance (chunk-2CHT42SU.js?v=182ba9fc:9512:15)
    at updateHostComponent (chunk-2CHT42SU.js?v=182ba9fc:14789:13)
    at beginWork (chunk-2CHT42SU.js?v=182ba9fc:15923:22)
    at beginWork$1 (chunk-2CHT42SU.js?v=182ba9fc:19749:22)
    at performUnitOfWork (chunk-2CHT42SU.js?v=182ba9fc:19194:20)
    at workLoopConcurrent (chunk-2CHT42SU.js?v=182ba9fc:19185:13)
    at renderRootConcurrent (chunk-2CHT42SU.js?v=182ba9fc:19160:15)
    at performConcurrentWorkOnRoot (chunk-2CHT42SU.js?v=182ba9fc:18674:46)
    at workLoop (chunk-2CHT42SU.js?v=182ba9fc:197:42)
    ...

After reload page styles are applied again.  In chrome it works ok.

**Comment by anyuruf** [comment]
And how did you configure the theming? May be you using localstorage?
